server:
  port: 8080

##DB properties
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_SERVER_ADDRESS:localhost}:5432/batch-processing
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


